#!/bin/sh
#* guix-shell — Run a command in a Guix environment suitable for Clasp
#
# SPDX-FileCopyrightText: Copyright (c) 2024 Paul A. Patience <paul@apatience.com>
# SPDX-License-Identifier: MIT

script_dir="$(dirname -- "$(realpath -- "$0")")"

if test -L "$script_dir/.guix_profile"; then
  guix shell --pure --profile="$script_dir/.guix_profile" -- "$@"
else
  guix shell --pure --root="$script_dir/.guix_profile" \
    -D -f "$script_dir/guix/clasp.scm" -- "$@"
fi
